### ISSUE TITLE
I made an icon, what do you think?

### ISSUE THREAD

**Issue by 5ee1e** [Zinhao/Kikoeru-android#3]
I came up with a design that would be good if I were to design it in my spare time.
If you are okay with me sending a pull request including this, I'd be happy to include it (it's not mandatory or anything, so if you're not interested, you can just CLOSE it).
Maybe the pixel count is wrong, but I can adjust it appropriately so it fits.

![](https://cdn.discordapp.com/attachments/757393787730395146/1002628743430418442/logo.png)

**Comment by Zinhao** [comment]
That is great！Can you read Chinese? 我们可以使用中文交流，我中文比较熟练。

**Comment by 5ee1e** [comment]
好的。
我对中国语言本身并无异议。
从现在开始，当我发送拉动请求或问题时，我将使用中文。

**Comment by JinhaoLi** [comment]
OUT TIME
